 create table course (course_id bigint generated by default as identity, course_name varchar(255), primary key (course_id))
 create table student (student_id bigint generated by default as identity, student_name varchar(255), primary key (student_id))
 create table student_course (course_id bigint not null, student_id bigint not null, primary key (course_id, student_id))
 alter table student_course add constraint FKq7yw2wg9wlt2cnj480hcdn6dq foreign key (student_id) references student
 alter table student_course add constraint FKejrkh4gv8iqgmspsanaji90ws foreign key (course_id) references course